eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
name:
  value: hemanth
management:
  tracing:
    sampling:
      probability: 1.0