server:
  port: 8222
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/customers/**
        - id: order-service
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/orders/**
        - id: order-lines-service
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/order-lines/**
        - id: product-service
          uri: http://localhost:8050
          predicates:
            - Path=/api/v1/products/**