server:
  port: 8040
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: notification
kafka:
  consumer:
    bootstrap-servers: localhost:9092
    group-id: order-consumer,payment-consumer
    auto-offset-reset: latest
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring.json.trusted.packages: '*'
      spring.json.type.mapping: orderConfirmation:com.eCommerce.Notification.kafka.order.OrderConfirmation,paymentConfirmation:com.eCommerce.Notification.kafka.payment.PaymentConfirmation
logging:
  level:
    org:
      springframework:
        kafka: DEBUG

mail:
  host: localhost
  port: 1025
  username: hemanth
  password: hemanth
  properties:
    mail:
      smtp:
        trust: "*"
      auth: true
      starttls:
        enabled: true
      connectiontimeout: 5000
      timeout: 3000
      writetimeout: 5000